workshop/workshop26/student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns= [
    path('',views.list,name="list"),
    path('create/',views.create, name="create"),
    ]

workshop/workshop26/workshop26/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include("student.urls")),
]

workshop/workshop26/student/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    
    def __str__(self):
        return self.name

workshop/workshop26/student/forms.py
from django import forms

class StudentForm(forms.Form):
    name = forms.CharField(max_length=100)
    age = forms.IntegerField()

workshop/workshop26/student/views.py
from django.shortcuts import render, redirect
from .models import Student
from .forms import StudentForm 
# Create your views here.


def list(request):
    students = Student.objects.all()
    return render(request,"student/list.html",{"students":students})
    
def create(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            age = form.cleaned_data.get("age")
        
            Student.objects.create(name=name,age=age)
            
            return redirect("student:list")

    else:
        return render(request,"student/create.html")
    

    
    

workshop/workshop26/student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'student:create' %}">글 작성하기</a>
    {% block bb %}
    {% endblock %}
</body>
</html>

workshop/workshop26/student/templates/student/create.html
{% extends 'student/base.html' %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="name"/>
        <input type="text" name="age"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

workshop/workshop26/student/templates/student/list.html
{% extends 'student/base.html' %}
{% block bb %}
    {% for student in students %}
        <h1>{{student.name}}</h1>
    {% endfor %}
{% endblock %}